[package]
name = "web_socket"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
futures-util = "0.3.31"
libc = "0.2.169"
rlimit = "0.10.2"
tokio = {version = "1.43.0", features = ["full"]}
tokio-tungstenite = "0.26.1"
warp = "0.3.7"
